### ISSUE TITLE
Main 페이지를 tailwindcss로 구현한다.

### ISSUE THREAD

**Issue by nyun-nye** [p-factory/p-factory#20]
## ⚠️Issue
- Main 페이지를 tailwindcss로 구현한다.
> components 분리 작업은 하지 않습니다.
> Header, Footer는 현재 디자인에 없어서 제외하고 진행한다.

## ✏️Task
- [ ] 시작 페이지를 tailwindcss로 구현한다.
- [ ] ㅍ토리 사용법 페이지를 tailwindcss로 구현한다.

## 🗓Next Task
-

**Comment by 4BFC** [comment]
@nyun-nye 기대하고 있겠습니다.

**Comment by nyun-nye** [comment]
### 메인페이지 관련 수정사항

- fontStyles.utils.js 내부의 fontSizes에 `--font-main` 사이즈를 추가했습니다. 메인페이지의 로고에 사용하기 위함입니다.
- Figma 디자인의 몇몇 값들이 소수점으로 되어 있는 문제
  - 협의 후 소수점 뒷자리를 제외했습니다.
    - 로고 글씨 (83.3px->83px)
    - 버튼 width (346.53px->346px)
    - 버튼 radius (16.83px -> 16px)
    - Click me!!! ~ 글씨 (15.84px -> `--font-xs`(16px))
  - mainStyles.components.js의 buttonComponents를 수정했습니다. 
    - Figma 디자인 상 동일한 버튼의 컴포넌트 radius 부분의 사이즈가 전부 달라 협의 후 `rounded-2xl`로 설정하여 통일했습니다. (16px)
    - 버튼 내부의 글씨를 가운데 정렬하기 위해 `flex`와 `justify-center` 속성을 추가했습니다.
    - 통일된 버튼 디자인에 맞춰 `.btn-primary`의 `text-white`를 `text-black`으로 수정했습니다.
    - 통일된 버튼 디자인에 맞춰 `.btn-primary`와 `.btn-secondary`의 font를 `font-medium`으로 통일했습니다.
- 토리와 함께 내가 만들어가는 ~ 글씨에서만 사용하는 `#b7b7b7` 색상을 Click me!!! ~ 에서의 색상과 동일하게 임의로 `statusColor-05`로 지정하였습니다.

>모든 변경 사항은 프론트 팀 내부에서 회의 후 임의로 지정한 것이며 협의 후 디자인 팀과 의견을 조율할 예정입니다. 따라서 변동이 있을 수 있습니다.

**Comment by 4BFC** [comment]
> ### 메인페이지 관련 수정사항
> * fontStyles.utils.js 내부의 fontSizes에 `--font-main` 사이즈를 추가했습니다. 메인페이지의 로고에 사용하기 위함입니다.
> * Figma 디자인의 몇몇 값들이 소수점으로 되어 있는 문제
>   
>   * 협의 후 소수점 뒷자리를 제외했습니다.
>     
>     * 로고 글씨 (83.3px->83px)
>     * 버튼 width (346.53px->346px)
>     * 버튼 radius (16.83px -> 16px)
>     * Click me!!! ~ 글씨 (15.84px -> `--font-xs`(16px))
>   * mainStyles.components.js의 buttonComponents를 수정했습니다.
>     
>     * Figma 디자인 상 동일한 버튼의 컴포넌트 radius 부분의 사이즈가 전부 달라 협의 후 `rounded-2xl`로 설정하여 통일했습니다. (16px)
>     * 버튼 내부의 글씨를 가운데 정렬하기 위해 `flex`와 `justify-center` 속성을 추가했습니다.
>     * 통일된 버튼 디자인에 맞춰 `.btn-primary`의 `text-white`를 `text-black`으로 수정했습니다.
>     * 통일된 버튼 디자인에 맞춰 `.btn-primary`와 `.btn-secondary`의 font를 `font-medium`으로 통일했습니다.
> * 토리와 함께 내가 만들어가는 ~ 글씨에서만 사용하는 `#b7b7b7` 색상을 Click me!!! ~ 에서의 색상과 동일하게 임의로 `statusColor-05`로 지정하였습니다.
> 
> > 모든 변경 사항은 프론트 팀 내부에서 회의 후 임의로 지정한 것이며 협의 후 디자인 팀과 의견을 조율할 예정입니다. 따라서 변동이 있을 수 있습니다.

의문이 들어서 멘트 남깁니다. Tailwind의 기본 제공의 유틸리티를 가지고 작업하시는게 아니라 tailwind 커스텀 컴포넌트나, 유틸리티를 추가한 이유가 무엇인가요?

**Comment by nyun-nye** [comment]
늦은 시간에도 읽어봐주셔서 감사합니다. 질문하신 부분 답변드립니다.
- `--font-main` 사이즈를 추가한 것은 추후에 사용할 수 있을 것 같았으니 디자인을 확인해보니 한 곳에서만 사용되는 것을 확인했습니다. 이는 커스텀 된 사이즈를 제거하고 `text-[83px]`로 수정할 계획입니다.
- 버튼 컴포넌트의 경우 거의 모든 페이지에서 동일한 디자인으로 활용되는 것을 확인하여 변경하였습니다.

확인하실 수 있도록 작업한 내용 push 하겠습니다!

**Comment by 4BFC** [comment]
> 늦은 시간에도 읽어봐주셔서 감사합니다. 질문하신 부분 답변드립니다.
> 
> * `--font-main` 사이즈를 추가한 것은 추후에 사용할 수 있을 것 같았으니 디자인을 확인해보니 한 곳에서만 사용되는 것을 확인했습니다. 이는 커스텀 된 사이즈를 제거하고 `text-[83px]`로 수정할 계획입니다.
> * 버튼 컴포넌트의 경우 거의 모든 페이지에서 동일한 디자인으로 활용되는 것을 확인하여 변경하였습니다.
> 
> 확인하실 수 있도록 작업한 내용 push 하겠습니다!

저도 동의합니다. 만약 필요하다면 네이밍은 `--font-logo`가 더 정체성이 뚜렷한거 같습니다.

**Comment by nyun-nye** [comment]
현재는 `--font-main`을 제거하고 사용할 계획이나 추후 필요 시 조언을 참고하여 `--font-logo` 네이밍을 고려해보도록 하겠습니다! 감사합니다.

**Comment by 4BFC** [comment]
> 현재는 `--font-main`을 제거하고 사용할 계획이나 추후 필요 시 조언을 참고하여 `--font-logo` 네이밍을 고려해보도록 하겠습니다! 감사합니다.

네 알겠습니다. Btn 관련 컴포넌트 작업을 미리 하신거 같은데 현제는 미리 나누어서 작업하는 과정은 아닙니다. 물론 버튼 부분이 추후에 컴포넌트로 나뉘어 지는것도 사실이지만 _utilsCSS_-[value]와 같이 직접 명시를 통해 동적으로 변동이 가능하다는걸 표기 하기 위함으로 생각하고 있었습니다. 하나의 예로 css 파일로 작업함과 inlineStyle로 작업함의 차이는 그라운드 룰에서 또는 협의 되지 않은 미정의 디자인 시스템 또는 css를 구별하기 위해서도 이 둘을 나누어 사용합니다. 따라 Styles 디렉토리에는 가급적 규약된 부분들, 검토와 점검이 된 부분들을 넣고 동적으로 변하거나 변동, 미정인 경우는 tailwindcss의 utils 직접 지정 방식으로 진행하면 좋을 듯합니다.

**Comment by 4BFC** [comment]
> 예시를 들어서 설명해주시니 한 번에 이해가 됐습니다. 앞으로 진행하는 코드들은 조언해주신 내용 참고하여 작성하겠습니다.

네, 감사합니다. 내일 디테일하게 설명이 다시 필요하시면 말씀해주시면 감사하겠습니다.
참고로 저 위의 규칙은 절대적임은 아닙니다. 때에 따라 tailwindcss 직접 지정 방식이 규칙으로 적용되며, 그렇게 사용하기도 합니다.⚠️🔥🔥

**Comment by 4BFC** [comment]
@nyun-nye width값으로 시용하는 것과 padding으로 사용하는 것의 기준과 차이가 명확하면 좋겠습니다. 한번 고민해주시고 코멘트 달아주시면 조율 후 따르겠습니다.
