### ISSUE TITLE
라이브러리를 설치한다. 

### ISSUE THREAD

**Issue by nyun-nye** [p-factory/p-factory#9]
## ⚠️Issue
- 필요한 라이브러리를 설치한다.

## ✏️Task
- 프로젝트에서 사용될 라이브러리들을 설치한다.

## 🗓Next Task
- [x] #12

**Comment by 4BFC** [comment]
@nyun-nye 
갑작스러운 회의에 시간을 내주어서 감사합니다. 회의 마지막에 말씀드렸던 부분에 관한 내용입니다. 꼭 확인해주시고 코멘트 남겨주시면 감사하겠습니다.
 현재 github code branch의 feature/9를 확인해보면 `node_modules`가 들어가 있습니다. 
![image](https://github.com/user-attachments/assets/94011e0f-a73d-4caf-b65a-fb65fe2b4b7e)
따라서 `.gitignore`를 설정하고 다시 작업을 하신다 해도 암묵적으로 node_modules가 포함되어 있는 상태에서 `git add ~`, `git commit ~`이 포함 되어 있기 때문에 아래와같은 명령어를 한번 수행해주시길 바랍니다.
`git rm -r --cached node_modules`
해당 명령어는 `git cache` 에 암묵적으로 포함되어 있는 `node_modules`를 제거하는 명령어입니다. 작업을 완료하고 push하기 전, 해당 명령어로 `node_modules`부분만 제거해주시면 됩니다.

**Comment by 4BFC** [comment]
@nyun-nye 추가적으로 pr-template도 수정했습니다. 따라 작업하고 계신 브랜치에서 `git pull origin main` 명령어를 주시면 `.github` 디렉토리가 업데이트 되면서 `Merge`를 요청할 겁니다. `Merge`를 작업할 시 `수신 내용 수락`을 해주시면 됩니다. 변경된 `pr-template`의 본문 내용은 다음 아래와 같습니다.
> main branch : [🌱: pr-template 수정](https://github.com/p-factory/p-factory/commit/3d011835ab48ca5e1107fc06b399274a039d46b7 "🌱: pr-template 수정")

**Comment by nyun-nye** [comment]
확인했습니다! 감사합니다 😄
